amd_rv100: probing ports...                                                                                                       
        port: 3000 data: 28c                                                                                                      
        port: 3001 data: 2                                                                                                        
        port: 3002 data: 0                                                                                                        
        port: 3003 data: 0                                                                                                        
        port: 3004 data: 0                                                                                                        
        port: 3005 data: 8000000                                                                                                  
        port: 3006 data: 3080000                                                                                                  
        port: 3007 data: 30800                                                                                                    
        port: 3008 data: 308                                                                                                      
        port: 3009 data: c3000003                                                                                                 
        port: 300a data: c30000                                                                                                   
        port: 300b data: c300                                                                                                     
        port: 300c data: c3                                                                                                       
        port: 300d data: c000000                                                                                                  
        port: 300e data: c0000                                                                                                    
        port: 300f data: c00                                                                                                      
        port: 3010 data: c                                                                                                        
        port: 3011 data: 0                                                                                                        
        port: 3012 data: c0000000                                                                                                 
        port: 3013 data: c00000                                                                                                   
        port: 3014 data: 100c000                                                                                                  
        port: 3015 data: 100c0                                                                                                    
        port: 3016 data: 4000100                                                                                                  
        port: 3017 data: 4040001                                                                                                  
        port: 3018 data: 10040400                                                                                                 
        port: 3019 data: 100404                                                                                                   
        port: 301a data: 1004                                                                                                     
        port: 301b data: 1000010                                                                                                  
        port: 301c data: 2010000                                                                                                  
        port: 301d data: 4020100                                                                                                  
        port: 301e data: 40201                                                                                                    
        port: 301f data: 402                                                                                                      
        port: 3020 data: 1000004                                                                                                  
        port: 3021 data: 1010000                                                                                                  
        port: 3022 data: 10100                                                                                                    
        port: 3023 data: 101                                                                                                      
        port: 3024 data: 1000001                                                                                                  
        port: 3025 data: 10000                                                                                                    
        port: 3026 data: f000100                                                                                                  
        port: 3027 data: 10f0001                                                                                                  
        port: 3028 data: 10f00                                                                                                    
        port: 3029 data: 10f                                                                                                      
        port: 302a data: 1                                                                                                        
        port: 302b data: 0                                                                                                        
        port: 302c data: 0                                                                                                        
        port: 302d data: b0000000                                                                                                 
        port: 302e data: a3b00000                                                                                                 
        port: 302f data: 33a3b000                                                                                                 
        port: 3030 data: 5133a3b0                                                                                                 
        port: 3031 data: f05133a3                                                                                                 
        port: 3032 data: f05133                                                                                                   
        port: 3033 data: f051                                                                                                     
        port: 3034 data: 840000f0                                                                                                 
        port: 3035 data: 840000                                                                                                   
        port: 3036 data: 8400                                                                                                     
        port: 3037 data: 1000084                                                                                                  
        port: 3038 data: 10000                                                                                                    
        port: 3039 data: 100                                                                                                      
        port: 303a data: 1                                                                                                        
        port: 303b data: 1000000                                                                                                  
        port: 303c data: 10000                                                                                                    
        port: 303d data: 100                                                                                                      
        port: 303e data: 1                                                                                                        
        port: 303f data: 0                                                                                                        
        port: 3040 data: 0                                                                                                        
        port: 3041 data: 7000000                                                                                                  
        port: 3042 data: 70000                                                                                                    
        port: 3043 data: 8000700                                                                                                  
        port: 3044 data: 80007                                                                                                    
        port: 3045 data: 800                                                                                                      
        port: 3046 data: 8                                                                                                        
        port: 3047 data: 0                                                                                                        
        port: 3048 data: 0                                                                                                        
        port: 3049 data: 0                                                                                                        
        port: 304a data: 0                                                                                                        
        port: 304b data: 0                                                                                                        
        port: 304c data: 0                                                                                                        
        port: 304d data: 0                                                                                                        
        port: 304e data: 6000000                                                                                                  
        port: 304f data: 60000                                                                                                    
        port: 3050 data: 3000600                                                                                                  
        port: 3051 data: 48030006                                                                                                 
        port: 3052 data: 480300                                                                                                   
        port: 3053 data: 8004803                                                                                                  
        port: 3054 data: 80048                                                                                                    
        port: 3055 data: 2000800                                                                                                  
        port: 3056 data: 41020008                                                                                                 
        port: 3057 data: 60410200                                                                                                 
        port: 3058 data: ff604102                                                                                                 
        port: 3059 data: eff6041                                                                                                  
        port: 305a data: aff60                                                                                                    
        port: 305b data: eff                                                                                                      
        port: 305c data: f                                                                                                        
        port: 305d data: 0                                                                                                        
        port: 305e data: 0                                                                                                        
        port: 305f data: 3000000                                                                                                  
        port: 3060 data: 30000                                                                                                    
        port: 3061 data: 300                                                                                                      
        port: 3062 data: 3                                                                                                        
        port: 3063 data: 3000000                                                                                                  
        port: 3064 data: 30000                                                                                                    
        port: 3065 data: 300                                                                                                      
        port: 3066 data: 3                                                                                                        
        port: 3067 data: 3000000                                                                                                  
        port: 3068 data: 30000                                                                                                    
        port: 3069 data: 300                                                                                                      
        port: 306a data: 3                                                                                                        
        port: 306b data: 3000000                                                                                                  
        port: 306c data: 30000                                                                                                    
        port: 306d data: 300                                                                                                      
        port: 306e data: 3                                                                                                        
        port: 306f data: 0                                                                                                        
        port: 3070 data: 0                                                                                                        
        port: 3071 data: 0                                                                                                        
        port: 3072 data: 0                                                                                                        
        port: 3073 data: 0                                                                                                        
        port: 3074 data: 0                                                                                                        
        port: 3075 data: 0                                                                                                        
        port: 3076 data: 0                                                                                                        
        port: 3077 data: 0                                                                                                        
        port: 3078 data: 0                                                                                                        
        port: 3079 data: 80000000                                                                                                 
        port: 307a data: f800000                                                                                                  
        port: 307b data: 10f8000                                                                                                  
        port: 307c data: 10f80                                                                                                    
        port: 307d data: 10f                                                                                                      
        port: 307e data: 1                                                                                                        
        port: 307f data: 0                                                                                                        
        port: 3080 data: 0                                                                                                        
        port: 3081 data: 0                                                                                                        
        port: 3082 data: 0                                                                                                        
        port: 3083 data: 0                                                                                                        
        port: 3084 data: 0                                                                                                        
        port: 3085 data: 0                                                                                                        
        port: 3086 data: 0                                                                                                        
        port: 3087 data: 0                                                                                                        
        port: 3088 data: 0                                                                                                        
        port: 3089 data: 0                                                                                                        
        port: 308a data: 0                                                                                                        
        port: 308b data: 0                                                                                                        
        port: 308c data: 0                                                                                                        
        port: 308d data: 0                                                                                                        
        port: 308e data: 0                                                                                                        
        port: 308f data: 0                                                                                                        
        port: 3090 data: 0                                                                                                        
        port: 3091 data: 0                                                                                                        
        port: 3092 data: 0                                                                                                        
        port: 3093 data: 0                                                                                                        
        port: 3094 data: 0                                                                                                        
        port: 3095 data: 0                                                                                                        
        port: 3096 data: 0                                                                                                        
        port: 3097 data: 0                                                                                                        
        port: 3098 data: 0                                                                                                        
        port: 3099 data: 0                                                                                                        
        port: 309a data: 0                                                                                                        
        port: 309b data: 0                                                                                                        
        port: 309c data: 0                                                                                                        
        port: 309d data: 0                                                                                                        
        port: 309e data: 0                                                                                                        
        port: 309f data: 0                                                                                                        
        port: 30a0 data: 0                                                                                                        
        port: 30a1 data: 0                                                                                                        
        port: 30a2 data: 0                                                                                                        
        port: 30a3 data: 0                                                                                                        
        port: 30a4 data: 0                                                                                                        
        port: 30a5 data: 0                                                                                                        
        port: 30a6 data: 0                                                                                                        
        port: 30a7 data: 0                                                                                                        
        port: 30a8 data: 0                                                                                                        
        port: 30a9 data: 0                                                                                                        
        port: 30aa data: 0                                                                                                        
        port: 30ab data: 0                                                                                                        
        port: 30ac data: 0                                                                                                        
        port: 30ad data: 0                                                                                                        
        port: 30ae data: 0                                                                                                        
        port: 30af data: 0                                                                                                        
        port: 30b0 data: 0                                                                                                        
        port: 30b1 data: 0                                                                                                        
        port: 30b2 data: 1010001                                                                                                  
        port: 30b3 data: 2020200                                                                                                  
        port: 30b4 data: 30303                                                                                                    
        port: 30b5 data: 14000404                                                                                                 
        port: 30b6 data: 701c0006                                                                                                 
        port: 30b7 data: 802000                                                                                                   
        port: 30b8 data: 2409024                                                                                                  
        port: 30b9 data: 280a0                                                                                                    
        port: 30ba data: 2c0                                                                                                      
        port: 30bb data: 3                                                                                                        
        port: 30bc data: 0                                                                                                        
        port: 30bd data: 0                                                                                                        
        port: 30be data: 0                                                                                                        
        port: 30bf data: 0                                                                                                        
        port: 30c0 data: 0                                                                                                        
        port: 30c1 data: 0                                                                                                        
        port: 30c2 data: 0                                                                                                        
        port: 30c3 data: 0                                                                                                        
        port: 30c4 data: 0                                                                                                        
        port: 30c5 data: 0                                                                                                        
        port: 30c6 data: 0                                                                                                        
        port: 30c7 data: 0                                                                                                        
        port: 30c8 data: 0                                                                                                        
        port: 30c9 data: 0                                                                                                        
        port: 30ca data: 0                                                                                                        
        port: 30cb data: 0                                                                                                        
        port: 30cc data: 0                                                                                                        
        port: 30cd data: 0                                                                                                        
        port: 30ce data: 0                                                                                                        
        port: 30cf data: 0                                                                                                        
        port: 30d0 data: 0                                                                                                        
        port: 30d1 data: 0                                                                                                        
        port: 30d2 data: 0                                                                                                        
        port: 30d3 data: 0                                                                                                        
        port: 30d4 data: 0                                                                                                        
        port: 30d5 data: 0                                                                                                        
        port: 30d6 data: 0                                                                                                        
        port: 30d7 data: 0                                                                                                        
        port: 30d8 data: 0                                                                                                        
        port: 30d9 data: 0                                                                                                        
        port: 30da data: 0                                                                                                        
        port: 30db data: 0                                                                                                        
        port: 30dc data: 0                                                                                                        
        port: 30dd data: 0                                                                                                        
        port: 30de data: 1000000                                                                                                  
        port: 30df data: 1010000                                                                                                  
        port: 30e0 data: 10100                                                                                                    
        port: 30e1 data: 101                                                                                                      
        port: 30e2 data: 1                                                                                                        
        port: 30e3 data: 0                                                                                                        
        port: 30e4 data: 0                                                                                                        
        port: 30e5 data: 0                                                                                                        
        port: 30e6 data: 0                                                                                                        
        port: 30e7 data: 0                                                                                                        
        port: 30e8 data: 0                                                                                                        
        port: 30e9 data: 43000000                                                                                                 
        port: 30ea data: 44430000                                                                                                 
        port: 30eb data: 444300                                                                                                   
        port: 30ec data: 4443                                                                                                     
        port: 30ed data: 44                                                                                                       
        port: 30ee data: 0                                                                                                        
        port: 30ef data: 0                                                                                                        
        port: 30f0 data: 0                                                                                                        
        port: 30f1 data: 0                                                                                                        
        port: 30f2 data: 0                                                                                                        
        port: 30f3 data: 0                                                                                                        
        port: 30f4 data: 0                                                                                                        
        port: 30f5 data: 0                                                                                                        
        port: 30f6 data: 0                                                                                                        
        port: 30f7 data: 0                                                                                                        
        port: 30f8 data: 1000000                                                                                                  
        port: 30f9 data: 10000                                                                                                    
        port: 30fa data: 100                                                                                                      
        port: 30fb data: 1                                                                                                        
        port: 30fc data: 0                                                                                                        
        port: 30fd data: ff000000                                                                                                 
        port: 30fe data: ffff0000                                                                                                 
        port: 30ff data: ffffff00                                                                                                 
        port: 3100 data: ffffffff                                                                                                 
        port: 3101 data: ffffffff                                                                                                 
        port: 3102 data: ffffffff                                                                                                 
        port: 3103 data: ffffffff                                                                                                 
        port: 3104 data: ffffffff                                                                                                 
        port: 3105 data: ffffffff                                                                                                 
        port: 3106 data: ffffffff                                                                                                 
        port: 3107 data: ffffffff                                                                                                 
        port: 3108 data: ffffffff                                                                                                 
        port: 3109 data: ffffffff                                                                                                 
        port: 310a data: ffffffff                                                                                                 
        port: 310b data: ffffffff                                                                                                 
        port: 310c data: ffffffff                                                                                                 
        port: 310d data: ffffffff                                                                                                 
        port: 310e data: ffffffff                                                                                                 
        port: 310f data: ffffffff                                                                                                 
        port: 3110 data: ffffffff                                                                                                 
        port: 3111 data: ffffffff                                                                                                 
        port: 3112 data: ffffffff
